resource_group: "DevOps-ResourceGroup"
vm_size : "Standard_B1s"
instance_name : "devostest"
location : "koreacentral"
virtual_network_name : "soyoung-vnet"
ssh_keys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNhg+kdc20cKZquCFVEJQGZDi4AJZqmTEwth54adRP0vSiWBYBuzk+OrYUF8LDo5c9uSviJzkju6tFsaY05+sthMHmN3uAntDqCtZ67JJqBxIOuOZAjeIDjZMuGHUyxboGUYEgOjKApOYDQ9F5uvggciILeKdHcV8FAxSzluEEog5WUH0Ahj/Flknaf/ly7vdz5Vswmpko6Qd4JkeZwwG5EeNblNv8StEUrkx6E/8/3XR7O21R16pOGGXRdUIcChwdbYh2GtSYkgBj2tyvV9a5AuDJCj7A8JciBHXSRoIZ9cCbclgzP/ZZc01vhwSfa3Bn71D5ILIwTpXdKO3eKkn7eNjGOUDQPj6m7OH/p1xvV4rZk3f+d+pqAt06vtNQPbomTODXd/eTzMGEeo3eNNhXfcAvM1Me8s3sw9Q6LgWMmyxhMpVi3mL4k4OKG51YZKBacH6JEODLebVe9qfEu1ygfDHyWxchbOxjpX4fV4lC00sQ8/Cht1gIE9k4SPqa7Ik= generated-by-azure"

